# Generated by Django 3.2.6 on 2021-08-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='num',
            field=models.CharField(max_length=10),
        ),
    ]
