# Generated by Django 3.2.6 on 2021-08-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210814_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='num',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cell',
            new_name='telefone',
        ),
    ]
